export default {
  // UI
  CHANGE_THEME: 'CHANGE_THEME',
  UPDATE_BREAKPOINT: 'UPDATE_BREAKPOINT',
  ALERT_WARNING: 'ALERT_WARNING',
  ALERT_SUCCESS: 'ALERT_SUCCESS',
  ALERT_CLEAR: 'ALERT_CLEAR',
  UPDATE_BREAKPOINT: 'UPDATE_BREAKPOINT',
  GET_UNIQUE_ID: 'GET_UNIQUE_ID',
  THREE_RENDERER_CHANGE_STEP: 'THREE_RENDERER_CHANGE_STEP',

  // USER
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',
  USER_CHECK_REQUEST: 'USER_CHECK_REQUEST',
  USER_CHECK_SUCCESS: 'USER_CHECK_SUCCESS',
  USER_CHECK_FAILURE: 'USER_CHECK_FAILURE',

  // DATA
  DATA_FOR_APP_REQUEST: 'DATA_FOR_APP_REQUEST',
  DATA_FOR_APP_SUCCESS: 'DATA_FOR_APP_SUCCESS',
  DATA_FOR_APP_FAILURE: 'DATA_FOR_APP_FAILURE',

  DATA_FOR_LOGIN_REQUEST: 'DATA_FOR_LOGIN_REQUEST',
  DATA_FOR_LOGIN_SUCCESS: 'DATA_FOR_LOGIN_SUCCESS',
  DATA_FOR_LOGIN_FAILURE: 'DATA_FOR_LOGIN_FAILURE',

  DATA_FOR_HOME_REQUEST: 'DATA_FOR_HOME_REQUEST',
  DATA_FOR_HOME_SUCCESS: 'DATA_FOR_HOME_SUCCESS',
  DATA_FOR_HOME_FAILURE: 'DATA_FOR_HOME_FAILURE'
}